quarto-required: ">=1.3.0"
project:
  type: website

website:
  title: "Vicente Lavagnino"
  description: "CV made with Quarto"
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Español 🇪🇸"
        contents:
          - index.qmd
          - curriculum/software-engineering/software-engineering_es.qmd
      
      - section: "English 🇬🇧"
        contents:
          - curriculum/main/main_en.qmd
          - curriculum/software-engineering/software-engineering_en.qmd
   
      - icon: linkedin
        href: "https://www.linkedin.com/in/tu-perfil"
        tooltip: "LinkedIn"

resources:
  - CNAME

format:
  html:
    author-meta: "Vicente Lavagnino"
    lang: en
    toc: true
    toc-title: Contents
    toc-depth: 2
    anchor-sections: true
    reference-location: section
    css: styles.css
    mainfont: Source Sans Pro
    theme:
      light: cosmo
      dark: darkly
    
    pdf:
      lang: es
      toc: true
      toc-depth: 2
      number-sections: true
      highlight: true
      mainfont: Source Sans Pro
