quarto-required: ">=1.3.0"
project:
  type: website

website:
  title: "Vicente Lavagnino"
  description: "CV made with Quarto"
  sidebar:
    style: docked
    search: true
    contents:
      - text: "LinkedIn"
        href: "https://www.linkedin.com/in/vicentelavagnino/"
      
      - section: "English"
        contents:
          - index.qmd
          - curriculum/detailed/detailed_en.qmd
      
      - section: "Español"
        contents:
          - curriculum/one-page/one-page_es.qmd
          - curriculum/detailed/detailed_es.qmd

resources:
  - CNAME

format:
  html:
    author-meta: "Vicente Lavagnino"
    lang: en
    toc: true
    toc-title: Contents
    toc-depth: 2
    anchor-sections: true
    reference-location: section
    css: styles.css
    mainfont: Source Sans Pro
    theme:
      light: cosmo
      dark: darkly
    
  pdf:
    documentclass: developercv
    geometry: margin=0.1cm
    fontsize: 9pt
    include-in-header:
      text: |
        \usepackage{multicol}
        \setlength{\columnsep}{0mm}
        \usepackage{lipsum}
